jibyun/digital-okcc

app/Http/Controllers/API/BaseController.php, app/Http/Controllers/API/MemberList/CategoryController.php, app/Http/Services/MemberList/MemberListService.php, routes/api.php
- Restful API template
- Added api/okcc/category GET API in the route
=> Issue #25 Restful API Template

app/Http/Controllers/API/MemberList/CategoryController.php, app/Http/Controllers/API/MemberList/MemberController.php, app/Http/Controllers/API/MemberList/MemberListController.php, app/Http/Services/MemberList/MemberListService.php, app/Http/Services/MemberList/MemberService.php, routes/api.php
- Restful API template 추가
- routing table URI 변경
=> MemberList, Member Restful API template

app/Http/Controllers/Admin/AdminPagesController.php, app/Http/Controllers/Admin/UsersController.php, app/Http/Controllers/Auth/RegisterController.php, app/Notifications/UserRegistered.php, app/User.php, composer.json, config/mail.php, config/services.php, resources/views/admin/includes/users/create.blade.php, resources/views/admin/includes/users/delete.blade.php, resources/views/admin/includes/users/edit.blade.php, resources/views/admin/includes/users/show.blade.php, resources/views/admin/user.blade.php, routes/web.php
1. Complete register user
2. mailgun api set (You need to run "composer install")
=> Register User including Send Admin email

app/Code.php, app/Code_Category.php, app/Department_Tree.php, app/Http/Services/MemberList/MemberListService.php
사이드 메뉴 데이터 처리 완료했습니다.
많은 논의를 하다보니 기존에 초안보다 깔끔하게 처리가 된 것같습니다.
=> Kw develop menu2

app/Http/Controllers/Admin/UsersController.php, public/css/chosen.css, resources/views/admin/includes/users/create.blade.php, resources/views/admin/includes/users/edit.blade.php, resources/views/admin/user.blade.php, routes/web.php
Since jQuery UI is uncomfortable, I changed it to autocomplete combo UI using Chosen. After that, I modified it's css to tune bootstrap 4.
=> Change autocomplete combo using jQuery UI to Chosen

app/Family_Map.php, app/Http/Controllers/Admin/FamilyTreesController.php, app/Http/Controllers/Admin/UsersController.php, resources/views/admin/category.blade.php, resources/views/admin/code.blade.php, resources/views/admin/family-tree.blade.php, resources/views/admin/includes/family-tree/add.blade.php, resources/views/admin/includes/family-tree/delete.blade.php, resources/views/admin/includes/family-tree/deleteall.blade.php, resources/views/admin/includes/family-tree/show.blade.php, resources/views/admin/privilege.blade.php, resources/views/admin/role.blade.php, routes/web.php
1. Added to create family tree
2. modified to use CKEDITOR (ver 4.9.1 -> ver 4.9.2)
=> added family tree and modified to CKEDITOR recent version

app/Http/Controllers/Rest/BaseController.php, app/Http/Controllers/Rest/MemberList/CategoryController.php, app/Http/Controllers/Rest/MemberList/MemberController.php, app/Http/Controllers/Rest/MemberList/MemberListController.php, app/Http/Controllers/Rest/MemberList/SearchController.php, app/Http/Controllers/Rest/Util/UtilsController.php, public/js/MemberList/memberList.js, resources/views/auth/register.blade.php, routes/api.php, routes/web.php
- Move the memberlist route to web.php
- Added to check auth in restful api
- fixed the preregister routing issue
=> Move restful api to web.php and protect via Auth

app/Http/Controllers/Admin/MemDeptMapsController.php, app/Http/Controllers/Admin/UsersController.php, app/Member_Department_Map.php, database/seeds/Code_CategoriesTableSeeder.php, database/seeds/CodesTableSeeder.php, resources/views/admin/family-tree.blade.php, resources/views/admin/includes/mem-dept-map/add.blade.php, resources/views/admin/includes/mem-dept-map/delete.blade.php, resources/views/admin/includes/mem-dept-map/edit.blade.php, resources/views/admin/includes/mem-dept-map/show.blade.php, resources/views/admin/layouts/header.blade.php, resources/views/admin/m-dept-map.blade.php, routes/web.php
1. Add member & department mapping
2. Add the method to read the current User ( to use in Javascript(jQuery) )
3. Add Position Seed in Categories and Codes (Sample Data for testing)
4. Add displaying current user on Top area
=> Add member & department mapping plus

app/Http/Controllers/Rest/MemberList/MemberListController.php, app/Http/Services/MemberList/MemberListService.php, database/seeds/Code_CategoriesTableSeeder.php, public/js/MemberList/memberList.js, resources/lang/en/messages.php, resources/views/MemberList/mainPanel.blade.php, routes/web.php
- Check Auth for memberList page
- MemberList main contents template
- Retrieve memberList by Duty
=> MemberList Main contents templast and retrieve memberList by Duty

database/migrations/2018_04_06_084929_create_member_department_maps_table.php, database/seeds/Code_CategoriesTableSeeder.php
- Changed the position_id as nullable
- Changed the default fieldName value
=> member_department_map column and code_categories seed change.

app/Http/Services/MemberList/MemberListService.php, app/Member.php
- retrieve memberList by Department
=> Retreive memberList by Department

public/css/okcc.css, public/js/MemberList/memberList.js, resources/lang/en/messages.php, resources/views/MemberList/mainPanel.blade.php, resources/views/MemberList/memberList.blade.php, resources/views/layouts/header.blade.php, routes/web.php
#74 MemberView Template for front-end
=> #74 MemberView Template for front-end

app/Http/Controllers/Auth/LoginController.php
After login redirect to memberList page
=> After login, redirect to memberList page

app/Http/Controllers/Rest/MemberList/MemberListController.php, app/Http/Services/MemberList/MemberListService.php, config/app.php, public/js/MemberList/memberList.js, resources/views/MemberList/mainPanel.blade.php, routes/web.php
#45 #58 MemberList Landing page
=> #45 #58 MemberList Landing page

app/Http/Controllers/Admin/AdminPagesController.php, app/Http/Controllers/Admin/Code_CategoriesController.php, app/Http/Controllers/Admin/CodesController.php, app/Http/Controllers/Admin/DepartmentTreesController.php, app/Http/Controllers/Admin/FamilyTreesController.php, app/Http/Controllers/Admin/LogController.php, app/Http/Controllers/Admin/MemDeptMapsController.php, app/Http/Controllers/Admin/MembersController.php, app/Http/Controllers/Admin/Privilege_Role_MapsController.php, app/Http/Controllers/Admin/PrivilegesController.php, app/Http/Controllers/Admin/RolesController.php, app/Http/Controllers/Admin/UsersController.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Services/Log/SystemLog.php, resources/lang/en/messages.php, resources/views/admin/logview.blade.php, routes/web.php
SystemLog::($code_id, $memo)
SystemLog::createLogForUpdatedFields($origin, $updated, $except) - 어차피 update record의 필드를 체크하여 description message를 만드는 기능으로 이곳이 적절하다고 생각되어 이곳에 둠
=> Adjust Log util path

app/Http/Services/MemberList/MemberListService.php, app/Member.php, app/Privilege.php, app/User.php, public/css/okcc.css, public/js/okcc.js, resources/views/MemberList/memberList.blade.php, resources/views/layouts/header.blade.php
#89 display memberlist in the table. (department as well)
#92 check user role utility
=> member table and user role utility

app/Http/Controllers/Admin/UsersController.php, app/Http/Controllers/Auth/RegisterController.php, app/Member_Department_Map.php, database/migrations/2018_04_04_084629_create_members_table.php, database/migrations/2018_04_06_083106_create_users_table.php, database/migrations/2018_04_06_084929_create_member_department_maps_table.php, database/seeds/MembersTableSeeder.php, resources/lang/en/messages.php, resources/views/admin/includes/mem-dept-map/add.blade.php, resources/views/admin/includes/mem-dept-map/disp.blade.php, resources/views/admin/includes/mem-dept-map/edit.blade.php, resources/views/admin/includes/members/edit.blade.php, resources/views/admin/includes/members/show.blade.php, resources/views/admin/m-dept-map.blade.php, resources/views/admin/member.blade.php
and change tinyint to boolean of primary in members table... internally same.
=> delete started_at finished_at in member-department table 

app/Http/Controllers/Admin/Code_CategoriesController.php, app/Http/Controllers/Admin/CodesController.php, app/Http/Controllers/Admin/DepartmentTreesController.php, app/Http/Controllers/Admin/FamilyTreesController.php, app/Http/Controllers/Admin/MemDeptMapsController.php, app/Http/Controllers/Admin/MembersController.php, app/Http/Controllers/Admin/Privilege_Role_MapsController.php, app/Http/Controllers/Admin/PrivilegesController.php, app/Http/Controllers/Admin/RolesController.php, app/Http/Controllers/Admin/UsersController.php, app/Http/Controllers/Auth/RegisterController.php, app/Member_Department_Map.php, database/migrations/2018_04_06_084929_create_member_department_maps_table.php, public/js/admin.js, resources/lang/en/messages.php, resources/views/admin/category.blade.php, resources/views/admin/code.blade.php, resources/views/admin/dept-tree.blade.php, resources/views/admin/family-tree.blade.php, resources/views/admin/includes/mem-dept-map/add.blade.php, resources/views/admin/includes/mem-dept-map/edit.blade.php, resources/views/admin/includes/mem-dept-map/show.blade.php, resources/views/admin/logview.blade.php, resources/views/admin/m-dept-map.blade.php, resources/views/admin/p-role-map.blade.php, resources/views/admin/privilege.blade.php, resources/views/admin/role.blade.php, resources/views/admin/user.blade.php
1. Feature Increment of Error Handling
2. Add manager field to member_department_map
3. Modify member_department_map CRUD
=> Feature Increment of Error Handling

app/Http/Controllers/Rest/MemberList/MemberListController.php, app/Http/Controllers/Rest/MemberList/SearchController.php, app/Http/Services/MemberList/CommonService.php, app/Http/Services/MemberList/MemberListService.php, app/Http/Services/MemberList/SearchService.php, public/js/MemberList/memberList.js, resources/views/MemberList/headerPanel.blade.php, resources/views/MemberList/mainPanel.blade.php
#101 show additional info for department
=>  #101 show additional info for department

app/Http/Controllers/Admin/AdminPagesController.php, config/session.php, resources/views/admin/layouts/master.blade.php
1. Implement Session timeout: When timeout, redirect to login.
2. fix some bugs for menu control
=> Session Timeout

app/Exports/MembersExport.php, app/Http/Controllers/Admin/ExportsController.php, app/Http/Controllers/Rest/MemberList/ExportController.php, public/js/MemberList/memberList.js, resources/lang/en/messages.php, resources/views/MemberList/exportDialog.blade.php, resources/views/MemberList/mainPanel.blade.php, resources/views/MemberList/tableToolbar.blade.php, resources/views/layouts/master.blade.php, routes/web.php
=> #105 export function

app/Exports/MembersExport.php, public/js/okcc.js, resources/lang/en/messages.php, resources/views/MemberList/memberList.blade.php, resources/views/layouts/header.blade.php, resources/views/layouts/master.blade.php
#144 Add admin page link in memberList
=> #144 Add admin page link in memberList

public/js/MemberList/memberList.js
#141 member status combo issue
=> #141 member status combo issue

app/Exports/MembersExport.php, app/Http/Controllers/Rest/MemberList/ExportController.php, app/Http/Services/MemberList/MemberListService.php, public/js/MemberList/memberList.js, resources/lang/en/messages.php
=> #145 export enhanced

resources/views/admin/members/department.blade.php
1. 부서로 편성할 때 여러종류의 Manager 직책, 여러종류의 Member 직책을 선택하여 조직할 수 있도록 변경함
=> Fix department organizer

database/migrations/2018_04_06_110716_create_visits_table.php
#155 Add paster_visitation field in visit table
=> #155 Add paster_visitation field in visit table

app/Http/Controllers/Admin/AdminPagesController.php, resources/views/admin/members/member.blade.php, resources/views/admin/tests/search.blade.php, routes/web.php
Bootstrap Table에 버그가 있어 고생 엄청 했음... 흐미...
Admin -> Tests -> Search Test 에 구현했으며, Member CRUD에만 실전 적용해 놓음.
=> Dynamic Search Control for ONLY Visible Column 

app/Http/Controllers/Admin/AdminPagesController.php, public/css/admin.css, public/js/admin.js, resources/lang/en/messages.php, resources/views/admin/contact.blade.php, resources/views/admin/includes/contact.blade.php, resources/views/admin/index.blade.php, resources/views/layouts/footer.blade.php, routes/web.php
=> Implement Contact Form

public/js/MemberList/memberDetail.js, public/js/MemberList/memberList.js, resources/views/MemberList/memberBasicInfoDialog.blade.php, resources/views/MemberList/memberSubPanel.blade.php
detail member info display edit . it's related issue #189 
remove display tab and family member info display modal.
=> issue #189 detail member info display edit
